version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bench-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: benchuser
      POSTGRES_PASSWORD: benchpass
      POSTGRES_DB: benchdb
    command: ["postgres", "-c", "max_connections=200"]
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    volumes:
      - pg_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    container_name: bench-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: benchpass
      MYSQL_DATABASE: benchdb
      MYSQL_USER: benchuser
      MYSQL_PASSWORD: benchpass
    command: --max-connections=200 --innodb-buffer-pool-size=1G
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    volumes:
      - mysql_data:/var/lib/mysql

  mariadb:
    image: mariadb:10.11
    container_name: bench-mariadb
    ports:
      - "3307:3306"  # inny port, żeby nie kolidował z MySQL
    environment:
      MARIADB_ROOT_PASSWORD: benchpass
      MARIADB_DATABASE: benchdb
      MARIADB_USER: benchuser
      MARIADB_PASSWORD: benchpass
    command: --max-connections=200 --innodb-buffer-pool-size=1G
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  pg_data:
  mysql_data:
  mariadb_data: